/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dictionary.java
 *
 * Created on Apr 19, 2010, 10:23:45 AM
 */

package buggymastercode;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.beanutils.DynaBean;
import org.jdesktop.application.Action;

/**
 *
 * @author jalvarez
 */
public class Dictionary extends javax.swing.JDialog {

    /** Creates new form Dictionary */
    public Dictionary(java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        // Events for jTable
        this.tblClasses.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                if (e.getClickCount() == 2)
                {
                    Point p = e.getPoint();
                    int row = tblClasses.rowAtPoint(p);
                    int id = Db.getId(tblClasses.getValueAt(row, 0));
                    editClass(id);
                    G.setRowSelectedById(tblClasses, id);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmdNew = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClasses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(528, 386));
        setName("Form"); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(buggymastercode.BuggyMasterCodeApp.class).getContext().getActionMap(Dictionary.class, this);
        cmdNew.setAction(actionMap.get("newClass")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(buggymastercode.BuggyMasterCodeApp.class).getContext().getResourceMap(Dictionary.class);
        cmdNew.setIcon(resourceMap.getIcon("cmdNew.icon")); // NOI18N
        cmdNew.setText(resourceMap.getString("cmdNew.text")); // NOI18N
        cmdNew.setFocusable(false);
        cmdNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNew.setName("cmdNew"); // NOI18N
        cmdNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdNew);

        cmdDelete.setAction(actionMap.get("deleteClass")); // NOI18N
        cmdDelete.setIcon(resourceMap.getIcon("cmdDelete.icon")); // NOI18N
        cmdDelete.setText(resourceMap.getString("cmdDelete.text")); // NOI18N
        cmdDelete.setFocusable(false);
        cmdDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdDelete.setName("cmdDelete"); // NOI18N
        cmdDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cmdDelete);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Packages", "Vb Class", "Java Class", "Functions", "Variables"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClasses.setName("tblClasses"); // NOI18N
        jScrollPane1.setViewportView(tblClasses);
        tblClasses.getColumnModel().getColumn(0).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title4")); // NOI18N
        tblClasses.getColumnModel().getColumn(1).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title5")); // NOI18N
        tblClasses.getColumnModel().getColumn(2).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(2).setPreferredWidth(3000);
        tblClasses.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title0")); // NOI18N
        tblClasses.getColumnModel().getColumn(3).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(3).setPreferredWidth(3000);
        tblClasses.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title1")); // NOI18N
        tblClasses.getColumnModel().getColumn(4).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(4).setPreferredWidth(800);
        tblClasses.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title2")); // NOI18N
        tblClasses.getColumnModel().getColumn(5).setMinWidth(100);
        tblClasses.getColumnModel().getColumn(5).setPreferredWidth(800);
        tblClasses.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tblClasses.columnModel.title3")); // NOI18N

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblClasses;
    // End of variables declaration//GEN-END:variables

    public boolean initDialog () {
        loadClasses();
        return true;
    }

    private boolean loadClasses() {
        try {
            DefaultTableModel model = (DefaultTableModel)this.tblClasses.getModel();
            model.getDataVector().removeAllElements();

            String sqlstmt = "select cl_id, cl_packagename, cl_vbname, cl_javaname from tclass";

            DBRecordSet rs = new DBRecordSet();
            if (!Db.db.openRs(sqlstmt, rs)) {return false;}

            // print the results
            for (Iterator<DynaBean> i = rs.getRows().iterator(); i.hasNext();) {
                DynaBean row = i.next();
                model.addRow(new Object[]{row.get("cl_id").toString(),
                                          row.get("cl_packagename").toString(),
                                          row.get("cl_vbname").toString(),
                                          row.get("cl_javaname").toString()});
            }
            return true;
        }
        catch(Exception ex) {
            BuggyMasterCodeApp.getLogger().log(Level.WARNING, "loading classes failed", ex);
            return false;
        }
    }

    public void editClass(int id) {
        if (classDialog == null) {
            JFrame mainFrame = BuggyMasterCodeApp.getApplication().getMainFrame();
            classDialog = new ClassDialog(mainFrame);
            classDialog.setLocationRelativeTo(mainFrame);
        }
        classDialog.edit(id);
        BuggyMasterCodeApp.getApplication().show(classDialog);
        loadClasses();
    }

    @Action
    public void newClass() {
        if (classDialog == null) {
            JFrame mainFrame = BuggyMasterCodeApp.getApplication().getMainFrame();
            classDialog = new ClassDialog(mainFrame);
            classDialog.setLocationRelativeTo(mainFrame);
        }
        classDialog.edit(Db.CS_NO_ID);
        BuggyMasterCodeApp.getApplication().show(classDialog);
        loadClasses();
        G.setRowSelectedById(tblClasses, classDialog.getId());
    }

    @Action
    public void deleteClass() {
        if (this.tblClasses.getRowCount() > 0) {
            int indexRow = this.tblClasses.getSelectedRow();
            Integer id = Db.getId(this.tblClasses.getValueAt(indexRow, 0));

            ClassObject cl = new ClassObject();
            cl.setId(id);
            if (cl.deleteClass()) {
                DefaultTableModel model = (DefaultTableModel)this.tblClasses.getModel();
                model.removeRow(indexRow);
            }
        }
    }

    private ClassDialog classDialog;

}
